// app.enums.js
export const ApiStatusCodes = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  DATA_NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export const ResponseMessages = {
  OK: "OK",
  CREATED: "CREATED",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  DATA_NOT_FOUND: "DATA_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
